# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bea6f8d5e1023c9afb4cd798dfcd922c"
application_url = "https://satisfied-cookie-camps-hurt.trycloudflare.com"
embedded = true
name = "Floatic: Connect Social Icons"
handle = "floatic-connect-social-icons"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://satisfied-cookie-camps-hurt.trycloudflare.com/auth/callback",
  "https://satisfied-cookie-camps-hurt.trycloudflare.com/auth/shopify/callback",
  "https://satisfied-cookie-camps-hurt.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "qbthemetest.myshopify.com"
automatically_update_urls_on_dev = true
